export class Company {
    constructor(
        public Company_id: number = 0,
        public PAUID: string = "",
        public CompanyLongName: string = "",
        public CompanyShortName: string = "",
        public NSD_Number: string = "",
        public CompanyCategory_id: number = 0,
        public CountryOfOrigin_id: number = 0,
        public CountryOfRegistration_id: number = 0,
        public RegistrationNumber: string = "",
        public TINNumber: string = "",
        public CompanyTelephone: string = "",
        public CompanyEmail: string = "",
        public CompanyWebsite: string = "",
        public CompanyEntityType_id: number = 0,
        public CompanyEntitySubType_id: number = 0,
        public CompanyMajorActivity_id: number = 0,
        public CompanyActivityDivision_id: number = 0,
        public CompanyActivityDivisionClass_id: number = 0,
        public CompanyActivityDivisionClassCategory_id: number = 0,
        public BusinessNatureDescription: string = "",
        public CompanyPostalAddress: string = "",
        public CompanyPhysicalAddress: string = "",
        public CompanyOtherEmails: string = "",
        public NSDQualificationDate: Date,
        public NSDQualificationYear: string = "",
        public PrimaryContactEntity: string = "",
        public ContactEntityEmail: string = "",
        public ContactEntityTelephone: string = "",
        public ContactEntityMobile: string = "",
        public ContactDesignation: string = "",
        public OperatorSortOrder: number = 0,
        public ContractorSortOrder: number = 0,
        public PAURegistrationDate: Date,
        public CraneNOGTRID: string = "",
        public TempNOGTRIPwd: string = "",
        public RegistrationStatus_id: number = 0,
        public ClassifyAsUgandan_id: number = 0,
        public Comments: string = "",
        public PrimaryCompanyKind_id: number = 0,
        public SecondaryCompanyKind_id: number = 0,
        public OtherCompanyKind_id: number = 0,
        public CompanyGroup_id: number = 0,
        public CompanyMobile: string = "",
        public CompanyFax: string = "",
        public ContactEntityFax: string = "",
        public NSD_FromDate: Date,
        public NSD_ToDate: Date,
        public ImportedFromNSD: number = 0,
        public ImportedDate: Date,
        public ExportedDate: Date,
        public ExportedToNogtr: number =0,
        public CreatedBy: string = "",
        public DateCreated: Date,
        public PreviousLegalName : string = "",
      ) { }

}
